api_login_check:
    path: /api/login_check

# app/config/routing.yml
app.swagger_ui:
    path: /api-doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

vadim_blog:
    resource: "@VadimBlogBundle/Resources/config/routing.yml"
    prefix:   /

users:
    type:     rest
    resource: Vadim\BlogBundle\Controller\Api\PostController
    prefix: /api
