security:

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    encoders:
        Vadim\BlogBundle\Entity\User: bcrypt

    providers:
        blog_users:
            entity: { class: Vadim\BlogBundle\Entity\User, property: email }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - vadim_blog.security.login_form_authenticator

            logout:
                path: /logout
            switch_user: ~
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
