services:
    vadim_blog.security.login_form_authenticator:
        class: Vadim\BlogBundle\Security\LoginFormAuthenticator
        arguments:
            - '@form.factory'
            - '@router'
            - '@security.password_encoder'

    vadim_blog_bundle_event_listener_hash_password_listener:
        class: Vadim\BlogBundle\EventListener\HashPasswordListener
        arguments:
            - '@security.password_encoder'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
